apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: config-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: config-service
spec:
  source:
    git:
      url: https://github.com/gm2552/config-service
      ref:
        branch: master
